# Generated by Django 3.2.6 on 2021-09-02 08:32

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='place')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(85.3178166, 27.6828417), srid=4326)),
            ],
        ),
    ]
