# Generated by Django 3.2.6 on 2022-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, default='media/place/kathmandu_durbar_square.png', upload_to='place'),
        ),
    ]
