# Generated by Django 3.2.6 on 2022-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, default='media/place/default.jpeg', upload_to='place'),
        ),
    ]
