# Generated by Django 3.2.6 on 2022-04-14 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.CharField(default='explicit', max_length=8),
        ),
    ]
