# Generated by Django 4.0.3 on 2022-04-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_place_photo'),
        ('map', '0005_auto_20220414_0543'),
    ]

    operations = [
    ]
