export default [{
    "title": "Ratna Park",
    "avg_rating": "2.5",
    "voted_by": "16",
    "genre": "['Parks']",
    "history": "False",
    "art_and_architecture": "False",
    "nature": "False",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Vijayapur Hill",
    "avg_rating": "4.5",
    "voted_by": "3",
    "genre": "['Points of Interest & Landmarks']",
    "history": "True",
    "art_and_architecture": "True",
    "nature": "True",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Banke National Park",
    "avg_rating": "4",
    "voted_by": "1",
    "genre": "['National Parks']",
    "history": "False",
    "art_and_architecture": "False",
    "nature": "True",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Char Narayan Temple",
    "avg_rating": "2.5",
    "voted_by": "11",
    "genre": "['Historic Sites', 'Religious Sites']",
    "history": "True",
    "art_and_architecture": "True",
    "nature": "False",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Thahiti Chowk",
    "avg_rating": "3.5",
    "voted_by": "18",
    "genre": "['Points of Interest & Landmarks', 'Monuments & Statues']",
    "history": "True",
    "art_and_architecture": "True",
    "nature": "True",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Temple and Statue of King Narasimha",
    "avg_rating": "3.5",
    "voted_by": "6",
    "genre": "['Religious Sites', 'Monuments & Statues']",
    "history": "True",
    "art_and_architecture": "True",
    "nature": "False",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "True",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Nara Devi Temple",
    "avg_rating": "4.5",
    "voted_by": "11",
    "genre": "['Points of Interest & Landmarks', 'Architectural Buildings']",
    "history": "True",
    "art_and_architecture": "True",
    "nature": "True",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}, {
    "title": "Bhinchhebahal",
    "avg_rating": "4.5",
    "voted_by": "4",
    "genre": "['Points of Interest & Landmarks']",
    "history": "True",
    "art_and_architecture": "True",
    "nature": "True",
    "adventure": "False",
    "entertainment": "False",
    "health_and_lifestyle": "False",
    "food": "False",
    "industries": "False",
    "religious": "False",
    "latitude": "",
    "longitude": "",
    "img_url": ""
}]