# Generated by Django 3.2.6 on 2022-04-13 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 16, 1, 45, 839551), verbose_name='date happened'),
        ),
    ]
